### PR TITLE
feat: add colour schemes, 17 main + 25 sceondary

### PR DESCRIPTION
**Pull request by VoodooHillbilly**
Add 17 main colour schemes
Add 25 secondary colour schemes
Update manifest to add colour schemes
Add an XCF template

### CODE REVIEW

**Comment by VoodooHillbilly** [comment]
I needed to reorganize some of the schemes. I just made dark mode versions of a couple of the themed ones instead of a separate dark mode. I came up with a couple more ideas, which pushed the totals way over half a dozen each.

There's a couple variations of the themed backgrounds missing. I haven't made them yet because they'd be almost identical to your Default and Bright secondary schemes. If you want me to, I could adjust the colors on those slightly to finish the sets I've made.

**Comment by Notexe** [comment]
Wow, great work with this!

> There's a couple variations of the themed backgrounds missing. I haven't made them yet because they'd be almost identical to your Default and Bright secondary schemes. If you want me to, I could adjust the colors on those slightly to finish the sets I've made.

Only if you think it's worth it.

**Comment by VoodooHillbilly** [comment]
No idea if it's worth it or not, but it may look a little better to have the complete set. At least to me anyway.

Would you rather merge this now and have me do another PR with that "enhancement:" comment the smf-mod uses, or smoosh them all into this PR?

**Review by Notexe — APPROVED** [review]
Looks fine to me

**Pull request merged**
